stop_speed_epsilon: 0.01
cmv_id: 123 # Test value; CARMA Streets expects cmv_id to be an unsigned long (32-bit unsigned integer)
cargo_id: "321" # Test value (Empty string indicates the vehicle is not carrying cargo); CARMA Streets expects cargo_id to be a string
enable_port_drayage: false # bool: Flag to activate and deactivate port drayage operations. If false, state machine will remain INACTIVE.